version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true